//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using System.Collections;
using UnityEngine;
using ColossalFramework;
using ColossalFramework.Globalization;
using ColossalFramework.UI;

namespace ResilientOwners
{
	public class ResilientUI : MonoBehaviour
	{

		ResilientBuildings m_info;

		ZonedBuildingWorldInfoPanel m_zonedBuildingInfoPanel;
		UIComponent m_bookInfoPanel;
		UIPanel m_extendedBuildingInfo;

		float m_bookInfoPanelInitialHeight = 0f;
		float m_bookInfoPanelLeftMargin = 20f;
		float m_bookInfoPanelLeftMarginPage2;
		float m_bookInfoPanelRightPadding = 20f;
		float m_bookInfoPanelPageWidth;
		float m_bookInfoPanelVerticalPadding = 20f;

		//Color32 m_bookTextColor = new Color32(148,175,199,255);
		//Color32 m_bookTextColor = new Color32(199,131,50,255);
		Color32 m_bookTextColor = Color.white;

		UILabel m_historyTitleLabel;
		UIMultilineTextField m_descriptionTextField;
		StatesButton m_resilientStateButton;
		UILabel m_familiesHistoryLabel;
		UILabel m_activatedDateLabel;
		UILabel m_statsLabel;
		UILabel m_statsLabel2;

		UICurrencyWrapper income =  new UICurrencyWrapper(0L);
		UIGoodsWrapper industryGoods =  new UIGoodsWrapper(0);
		UIGoodsWrapper industryGoods2 =  new UIGoodsWrapper(0);

		ushort m_currentSelectedBuildingID;

		public static ResilientUI Install(GameObject resilientGO, ResilientBuildings info, UIPanel extendedBuildingInfo)
		{
			ResilientUI rui = resilientGO.AddComponent<ResilientUI>();
			//ResilientUI rui = new ResilientUI();
			rui.m_info = info;

			rui.m_zonedBuildingInfoPanel = GameObject.Find("(Library) ZonedBuildingWorldInfoPanel").GetComponent<ZonedBuildingWorldInfoPanel>();

			if(extendedBuildingInfo != null)
			{
				rui.m_extendedBuildingInfo = extendedBuildingInfo;
				//rui.referenceExtendedBuildingsInfoModUIelements();
			}

			rui.AddComponents();

			return rui;
		}

		public static void Uninstall(ResilientUI rui)
		{

		}

		/********** UI building ***********/

		void AddComponents()
		{
			BookPanel bp = this.gameObject.AddComponent<BookPanel>();
			bp.transform.parent = m_zonedBuildingInfoPanel.component.transform;
			bp.size = new Vector3(m_zonedBuildingInfoPanel.component.size.x, m_zonedBuildingInfoPanel.component.size.y);
			bp.position = new Vector3(-bp.size.x-m_bookInfoPanelLeftMargin, +bp.size.y);
            //bp.position = new Vector3(-512, -512);

			m_bookInfoPanelInitialHeight = bp.height;
			m_bookInfoPanelPageWidth = bp.size.x/2 - m_bookInfoPanelLeftMargin - m_bookInfoPanelRightPadding;
			m_bookInfoPanelLeftMarginPage2 = bp.size.x/2 + m_bookInfoPanelLeftMargin;

			m_bookInfoPanel = bp;

			m_historyTitleLabel = m_bookInfoPanel.AddUIComponent<UILabel> ();
			m_historyTitleLabel.name = "History Title";
			m_historyTitleLabel.text = Localization.GetHistoryTitle();
			m_historyTitleLabel.textColor = m_bookTextColor;

			m_descriptionTextField = m_bookInfoPanel.AddUIComponent<UIMultilineTextField> ();
			m_descriptionTextField.name = "Building Description";
			m_descriptionTextField.text = "Enter description";
			m_descriptionTextField.textScale = 0.8f;
			m_descriptionTextField.width = m_bookInfoPanelPageWidth;
			m_descriptionTextField.height = 100f;
			m_descriptionTextField.disabledTextColor = new Color32(7, 7, 7, 255);
			m_descriptionTextField.textColor = m_bookTextColor;
			m_descriptionTextField.eventTextSubmitted += (component, param) =>
			{
				SaveDescription(param);
			};
//			m_descriptionTextField.title = "Description";
//			m_descriptionTextField.showTitle = true;
			m_descriptionTextField.defaultText = Localization.GetDescriptionEmpty();
			m_descriptionTextField.eventHeightChange += (component, height) => {
				ResizePanelHeight(height);
			};

			int spriteWidth = 32;
			int spriteHeight = 32;
			string[] tooltips = {
				Mod.modName+": disabled", 
				Mod.modName+": history is enabled",
				Mod.modName+": history and resiliency enabled"
			};
			m_resilientStateButton = new StatesButton(m_zonedBuildingInfoPanel.component, spriteWidth, spriteHeight, 3, "icons.book.png", "ResilientOwners", tooltips);

			m_resilientStateButton.msb.eventActiveStateIndexChanged += (component, value) => {

				if(!m_allowEvents)
					return;

				switch(value)
				{
				case 0:
					m_info.UnsuscribeBuilding(m_currentSelectedBuildingID);
					HideHistory();
					break;
				case 1:
					m_info.AddBuilding(m_currentSelectedBuildingID, false);
					ShowHistory();
					break;
				case 2:
					m_info.AddBuilding(m_currentSelectedBuildingID, true);
					ShowHistory();
					break;
				}
			};
			m_resilientStateButton.msb.AlignTo(m_zonedBuildingInfoPanel.component, UIAlignAnchor.TopRight);
			m_resilientStateButton.msb.relativePosition += new Vector3 (-50f, 90f, 0f);

			m_familiesHistoryLabel = m_bookInfoPanel.AddUIComponent<UILabel> ();
			m_familiesHistoryLabel.name = "Families History";
			m_familiesHistoryLabel.text = Localization.GetEmptyHouse();
			m_familiesHistoryLabel.textScale = 0.8f;
			m_familiesHistoryLabel.textColor = m_bookTextColor;
			m_familiesHistoryLabel.width = m_bookInfoPanelPageWidth;
			m_familiesHistoryLabel.wordWrap = true;
			m_familiesHistoryLabel.autoSize = false;
			m_familiesHistoryLabel.autoHeight = true;

			m_activatedDateLabel = m_bookInfoPanel.AddUIComponent<UILabel> ();
			m_activatedDateLabel.name = "Activation Date";
			m_activatedDateLabel.text = Localization.GetActivationDate();
			m_activatedDateLabel.textScale = 0.8f;
			m_activatedDateLabel.textColor = m_bookTextColor;
			m_activatedDateLabel.width = m_bookInfoPanelPageWidth;

			m_statsLabel = m_bookInfoPanel.AddUIComponent<UILabel> ();
			m_statsLabel.name = "Stats";
			m_statsLabel.text = Localization.GetAccumulatedIncome();
			m_statsLabel.textScale = 0.8f;
			m_statsLabel.textColor = m_bookTextColor;
			m_statsLabel.width = m_bookInfoPanelPageWidth;

			m_statsLabel2 = m_bookInfoPanel.AddUIComponent<UILabel> ();
			m_statsLabel2.name = "Stats 2";
			m_statsLabel2.text = "";
			m_statsLabel2.textScale = 0.8f;
			m_statsLabel2.textColor = m_bookTextColor;
			m_statsLabel2.width = m_bookInfoPanelPageWidth;

//			m_zonedBuildingInfoPanel.component.eveeventVisibilityChanged +=(component, param) =>
//			{
//				if(param)
//					OnSelected();
//			};

			//m_zonedBuildingInfoPanel.m_IsEmbbeded = true;//one of the condition call to OnPositionChanged, ensure it
			m_zonedBuildingInfoPanel.component.eventPositionChanged += (inst1, inst2) =>
			{
				if(m_zonedBuildingInfoPanel.component.isVisible)
					OnSelected();
			};

			m_zonedBuildingInfoPanel.component.eventOpacityChanged += (inst1, inst2) =>
			{
				if(m_zonedBuildingInfoPanel.component.isVisible)
					OnSelected();
			};


		}

		/********** Event Handlers ***************/

		bool m_allowEvents = true;
		void SaveDescription(string desc)
		{
			if (!m_allowEvents)
				return;
			int buildIndex = m_info.GetResilientBuildingIndex (m_currentSelectedBuildingID);
			if (buildIndex != -1) {
				ResilientBuildings.ResilientInfoV1 ri = m_info.m_resilients [buildIndex];
				ri.description = desc;
				m_info.m_resilients [buildIndex] = ri;
			}
		}

		/********** UI update methods ***************/

		void OnSelected()
		{
			//get selected building ID (after waiting it has been actualized)
			FieldInfo baseSub = m_zonedBuildingInfoPanel.GetType().GetField("m_InstanceID", BindingFlags.NonPublic | BindingFlags.Instance);
			InstanceID instanceId = (InstanceID)baseSub.GetValue(m_zonedBuildingInfoPanel);
			if (instanceId.Type == InstanceType.Building && instanceId.Building != 0) {
				if(m_currentSelectedBuildingID == instanceId.Building) //no update needed
					return;
				m_currentSelectedBuildingID = instanceId.Building;
			} else
			{
				m_currentSelectedBuildingID = 0;
			}

			int buildIndex = m_info.GetResilientBuildingIndex (m_currentSelectedBuildingID);
			m_allowEvents = false;
			if (buildIndex != -1) {
				if(m_info.m_resilients[buildIndex].resiliencyActivated)
					m_resilientStateButton.SetState(2);
				else
					m_resilientStateButton.SetState(1);
				ShowHistory();
				CheckUpdateUI(m_currentSelectedBuildingID);
			} else {
				m_resilientStateButton.SetState(0);
				HideHistory();
			}

			m_allowEvents = true;


			m_bookInfoPanel.Invalidate();
		}

		public void HideHistory()
		{
			m_descriptionTextField.isVisible = false;
			m_familiesHistoryLabel.isVisible = false;
			m_activatedDateLabel.isVisible = false;
			m_statsLabel.isVisible = false;
			m_statsLabel2.isVisible = false;
			m_bookInfoPanel.isVisible = false;
			if(m_extendedBuildingInfo != null)
			{
				showDescriptionExtendedBuildingsInfo();
			}
			//m_zonedBuildingInfoPanelComponent.height = m_zonedBuildingInfoPanelInitialHeight;
		}

		public void ShowHistory()
		{
			int buildIndex = m_info.GetResilientBuildingIndex (m_currentSelectedBuildingID);


			m_descriptionTextField.text = m_info.m_resilients [buildIndex].description;
			if(m_extendedBuildingInfo != null)
			{
				if(m_extendedBuildingInfoDescriptionButton == null)
					referenceExtendedBuildingsInfoModUIelements();
				if(m_info.m_resilients [buildIndex].description.Length == 0)
				{
					m_descriptionTextField.text = takeDescriptionFromExtendedBuildingsInfo();
				}
				hideDescriptionExtendedBuildingsInfo();
			}
			m_descriptionTextField.isVisible = true;

			if(Singleton<BuildingManager>.instance.m_buildings.m_buffer[m_currentSelectedBuildingID].Info.m_class.m_service == ItemClass.Service.Residential)
				m_familiesHistoryLabel.text = m_info.GetFamiliesList(buildIndex);
			else
				m_familiesHistoryLabel.text = m_info.GetWorkersHistoryList(buildIndex);
			m_familiesHistoryLabel.isVisible = true;

			m_activatedDateLabel.text = Localization.GetActivationDate() + ' ' + m_info.m_resilients [buildIndex].activatedDate.Date.ToString("dd/MM/yyyy");
			m_activatedDateLabel.isVisible = true;

			m_statsLabel.isVisible = true;
			m_statsLabel2.isVisible = true;

			m_bookInfoPanel.isVisible = true;

			ResizePanelHeight(0f);
		}

		float last_desc_height;
		public void ResizePanelHeight(float desc_height)
		{
			if(desc_height == 0f)
				desc_height = last_desc_height;

			desc_height = m_descriptionTextField.getComposedHeight();
			float hist_height = m_familiesHistoryLabel.height + m_activatedDateLabel.height + m_statsLabel.height + m_statsLabel2.height + 3*m_bookInfoPanelVerticalPadding;

			float add_height = Mathf.Max(desc_height, hist_height) + 2*m_bookInfoPanelVerticalPadding + m_historyTitleLabel.height;

			m_historyTitleLabel.AlignTo(m_bookInfoPanel, UIAlignAnchor.TopLeft);
			m_historyTitleLabel.relativePosition += new Vector3 (m_bookInfoPanelLeftMargin, m_bookInfoPanelVerticalPadding, 0f);

			m_familiesHistoryLabel.AlignTo(m_bookInfoPanel, UIAlignAnchor.TopLeft);
			m_activatedDateLabel.AlignTo(m_bookInfoPanel, UIAlignAnchor.TopLeft);
			m_statsLabel.AlignTo(m_bookInfoPanel, UIAlignAnchor.TopLeft);
			m_statsLabel2.AlignTo(m_bookInfoPanel, UIAlignAnchor.TopLeft);
			m_activatedDateLabel.relativePosition += new Vector3 (m_bookInfoPanelLeftMarginPage2, m_historyTitleLabel.height+m_activatedDateLabel.height+2*m_bookInfoPanelVerticalPadding, 0f);
			m_statsLabel.relativePosition += new Vector3 (m_bookInfoPanelLeftMarginPage2, m_historyTitleLabel.height+m_activatedDateLabel.height + 3*m_bookInfoPanelVerticalPadding, 0f);
			m_statsLabel2.relativePosition += new Vector3 (m_bookInfoPanelLeftMarginPage2, m_historyTitleLabel.height+m_activatedDateLabel.height+m_statsLabel.height + 4*m_bookInfoPanelVerticalPadding, 0f);
			m_familiesHistoryLabel.relativePosition += new Vector3 (m_bookInfoPanelLeftMarginPage2, m_historyTitleLabel.height+m_activatedDateLabel.height+m_statsLabel.height+m_statsLabel2.height + 5*m_bookInfoPanelVerticalPadding, 0f);

			m_familiesHistoryLabel.width = m_bookInfoPanelPageWidth;

			m_descriptionTextField.AlignTo(m_bookInfoPanel, UIAlignAnchor.TopLeft);
			m_descriptionTextField.relativePosition += new Vector3 (m_bookInfoPanelLeftMargin, 2*m_bookInfoPanelVerticalPadding+m_historyTitleLabel.height, 0f);

			if(add_height > m_bookInfoPanel.height)
				m_bookInfoPanel.height = /*m_zonedBuildingInfoPanelInitialHeight + */add_height;
			else
				m_bookInfoPanel.height = m_bookInfoPanelInitialHeight;

			last_desc_height = desc_height;

		}

		public void CheckUpdateUI(ushort buildingID)
		{
			if(m_currentSelectedBuildingID != buildingID)
				return;

			int buildIndex = m_info.GetResilientBuildingIndex (m_currentSelectedBuildingID);
			if(buildIndex != -1)
			{
				income.Check(m_info.m_resilients [buildIndex].totalIncome);
				m_statsLabel.text = Localization.GetAccumulatedIncome() + income.result;

				BuildingInfo buildinfo = Singleton<BuildingManager>.instance.m_buildings.m_buffer[m_currentSelectedBuildingID].Info;
				switch(buildinfo.m_class.m_service)
				{
					case ItemClass.Service.Commercial:
						m_statsLabel2.text = "Clients served : " + m_info.m_resilients [buildIndex].totalVisits + " - Inside now : " + m_info.m_resilients [buildIndex].currentVisits;
						break;
					case ItemClass.Service.Industrial:
					CODebug.Log(LogChannel.Modding, "examine AI "+buildinfo.m_buildingAI+" for "+Singleton<BuildingManager>.instance.GetBuildingName(m_currentSelectedBuildingID, default(InstanceID)));
						bool extractor = buildinfo.m_buildingAI.GetType().Equals(typeof(IndustrialExtractorAI));

						if(extractor)
						{
							industryGoods.Check(m_info.m_resilients [buildIndex].goodsBuffer2, buildinfo.m_class.m_subService, true);
							industryGoods2.Check(m_info.m_resilients [buildIndex].goodsBuffer3, buildinfo.m_class.m_subService, true);
							m_statsLabel2.text = "Exported : " + industryGoods.result +", Stock : " + industryGoods2.result;
						}
						else
						{
							industryGoods.Check(m_info.m_resilients [buildIndex].goodsBuffer2, buildinfo.m_class.m_subService, false);
							industryGoods2.Check(m_info.m_resilients [buildIndex].goodsBuffer4, buildinfo.m_class.m_subService, false);
							m_statsLabel2.text = "Imported : " + industryGoods.result +", Exported " + industryGoods2.result;
						}
						break;
					default:
						m_statsLabel2.isVisible = false;
						break;
				}
	
			}
		}

		//sync info with extended building mod

		UILabel m_extendedBuildingInfoDescriptionLabel;
		UIButton m_extendedBuildingInfoDescriptionButton;

		void referenceExtendedBuildingsInfoModUIelements()
		{
			UILabel[] labels = m_extendedBuildingInfo.gameObject.GetComponents<UILabel>();
			CODebug.Log(LogChannel.Modding, "number of labels = "+labels.Length);
			m_extendedBuildingInfoDescriptionLabel = labels[labels.Length-1];

			m_extendedBuildingInfoDescriptionButton = m_extendedBuildingInfo.gameObject.GetComponent<UIButton>();
		}

		string takeDescriptionFromExtendedBuildingsInfo()
		{
			if (m_extendedBuildingInfoDescriptionButton == null)
				return "";
			return m_extendedBuildingInfoDescriptionLabel.text;
		}

		void hideDescriptionExtendedBuildingsInfo()
		{
			if (m_extendedBuildingInfoDescriptionButton == null)
				return;
			m_extendedBuildingInfoDescriptionLabel.isVisible = false;
			m_extendedBuildingInfoDescriptionButton.isVisible = false;
		}

		void showDescriptionExtendedBuildingsInfo()
		{
			if (m_extendedBuildingInfoDescriptionButton == null)
				return;
			m_extendedBuildingInfoDescriptionLabel.isVisible = true;
			m_extendedBuildingInfoDescriptionButton.isVisible = true;
		}
	}
}

